In [2]:
# ==========================================
# 1. Import Libraries
# ==========================================

import pandas as pd
import numpy as np
import ast
import os

# ==========================================
# 2. Load Datasets
# ==========================================

movies = pd.read_csv("../dataset/movies.csv")
credits = pd.read_csv("../dataset/credits.csv")
keywords = pd.read_csv("../dataset/keywords.csv")

print("Movies :", movies.shape)
print("Credits:", credits.shape)
print("Keywords:", keywords.shape)

# ==========================================
# 3. Convert ID Columns to Integer
# ==========================================

movies["id"] = pd.to_numeric(movies["id"], errors="coerce")
credits["id"] = pd.to_numeric(credits["id"], errors="coerce")
keywords["id"] = pd.to_numeric(keywords["id"], errors="coerce")

movies = movies.dropna(subset=["id"])
credits = credits.dropna(subset=["id"])
keywords = keywords.dropna(subset=["id"])

movies["id"] = movies["id"].astype(int)
credits["id"] = credits["id"].astype(int)
keywords["id"] = keywords["id"].astype(int)

# ==========================================
# 4. Remove Duplicate Movie IDs
# ==========================================

movies = movies.drop_duplicates(subset="id", keep="first")
credits = credits.drop_duplicates(subset="id", keep="first")
keywords = keywords.drop_duplicates(subset="id", keep="first")

print("\nDuplicate IDs Remaining")
print("-----------------------")
print("Movies   :", movies["id"].duplicated().sum())
print("Credits  :", credits["id"].duplicated().sum())
print("Keywords :", keywords["id"].duplicated().sum())

# ==========================================
# 5. Merge Datasets
# ==========================================

ott_df = movies.merge(credits, on="id", how="left")
ott_df = ott_df.merge(keywords, on="id", how="left")

print("\nMerged Dataset Shape:")
print(ott_df.shape)

# ==========================================
# 6. Create Processed Folder (if it doesn't exist)
# ==========================================

os.makedirs("../dataset/processed", exist_ok=True)

# ==========================================
# 7. Save Merged Dataset
# ==========================================

ott_df.to_csv("../dataset/processed/merged_dataset.csv", index=False)

print("\nMerged dataset saved successfully!")

Movies : (45466, 12)
Credits: (45476, 3)
Keywords: (46419, 2)

Duplicate IDs Remaining
-----------------------
Movies   : 0
Credits  : 0
Keywords : 0

Merged Dataset Shape:
(45433, 15)

Merged dataset saved successfully!

In [3]:
print("Duplicate IDs in movies:", movies["id"].duplicated().sum())
print("Duplicate IDs in credits:", credits["id"].duplicated().sum())
print("Duplicate IDs in keywords:", keywords["id"].duplicated().sum())

Duplicate IDs in movies: 0
Duplicate IDs in credits: 0
Duplicate IDs in keywords: 0

In [4]:
#MOVIES

movies[movies["id"].duplicated(keep=False)].sort_values("id")

Empty DataFrame
Columns: [belongs_to_collection, budget, genres, id, original_language, overview, production_companies, production_countries, release_date, revenue, runtime, spoken_languages]
Index: []

In [5]:
#CREDITS

credits[credits["id"].duplicated(keep=False)].sort_values("id")

Empty DataFrame
Columns: [cast, crew, id]
Index: []

In [6]:
#KEYWORDS

keywords[keywords["id"].duplicated(keep=False)].sort_values("id")

Empty DataFrame
Columns: [id, keywords]
Index: []

In [7]:
movies = movies.drop_duplicates(subset="id", keep="first")

credits = credits.drop_duplicates(subset="id", keep="first")

keywords = keywords.drop_duplicates(subset="id", keep="first")

In [8]:
print(movies["id"].duplicated().sum())
print(credits["id"].duplicated().sum())
print(keywords["id"].duplicated().sum())

0
0
0

In [9]:
print(movies.columns.tolist())

['belongs_to_collection', 'budget', 'genres', 'id', 'original_language', 'overview', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages']

In [10]:
# Merge movies and credits
ott_df = movies.merge(credits, on="id", how="left")

# Merge keywords
ott_df = ott_df.merge(keywords, on="id", how="left")

print("Merged Shape:", ott_df.shape)

Merged Shape: (45433, 15)

In [11]:
ott_df["id"].duplicated().sum()

np.int64(0)

In [12]:
ott_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45433 entries, 0 to 45432
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4488 non-null   str
 1   budget                 45433 non-null  str
 2   genres                 45433 non-null  str
 3   id                     45433 non-null  int64
 4   original_language      45422 non-null  str
 5   overview               44479 non-null  str
 6   production_companies   45430 non-null  str
 7   production_countries   45430 non-null  str
 8   release_date           45346 non-null  str
 9   revenue                45430 non-null  float64
 10  runtime                45173 non-null  float64
 11  spoken_languages       45430 non-null  str
 12  cast                   45432 non-null  str
 13  crew                   45432 non-null  str
 14  keywords               45432 non-null  str
dtypes: float64(2), int64(1), str(12)
memory usage: 216.2 MB

In [13]:
ott_df.isnull().sum().sort_values(ascending=False)

belongs_to_collection    40945
overview                   954
runtime                    260
release_date                87
original_language           11
production_companies         3
production_countries         3
spoken_languages             3
revenue                      3
crew                         1
cast                         1
keywords                     1
id                           0
budget                       0
genres                       0
dtype: int64

In [14]:
ott_df.head()

,belongs_to_collection,budget,genres,id,original_language,overview,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,cast,crew,keywords
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",10/30/1995,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",12/15/1995,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",12/22/1995,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",12/22/1995,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",2/10/1995,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [15]:
ott_df.describe(include='all')

,belongs_to_collection,budget,genres,id,original_language,overview,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,cast,crew,keywords
count,4488,45433,45433,45433.000000,45422,44479,45430,45430,45346,4.543000e+04,45173.00000,45430,45432,45432,45432
unique,1695,1223,4066,NaN,89,44306,22707,2390,17333,NaN,NaN,1931,43019,44662,25989
top,"{'id': 415931, 'name': 'The Bowery Boys', 'pos...",0,"[{'id': 18, 'name': 'Drama'}]",NaN,en,No overview found.,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1/1/2008,NaN,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",[],[],[]
freq,29,36553,4996,NaN,32251,133,11868,17841,136,NaN,NaN,22381,2414,771,14340
mean,NaN,NaN,NaN,108375.226179,NaN,NaN,NaN,NaN,NaN,1.121288e+07,94.12430,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,112479.760366,NaN,NaN,NaN,NaN,NaN,6.435213e+07,38.41554,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.00000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,26461.000000,NaN,NaN,NaN,NaN,NaN,0.000000e+00,85.00000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,59996.000000,NaN,NaN,NaN,NaN,NaN,0.000000e+00,95.00000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,157351.000000,NaN,NaN,NaN,NaN,NaN,0.000000e+00,107.00000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,469172.000000,NaN,NaN,NaN,NaN,NaN,2.787965e+09,1256.00000,NaN,NaN,NaN,NaN

In [16]:
import pandas as pd

# Convert budget to numeric
ott_df["budget"] = pd.to_numeric(ott_df["budget"], errors="coerce")

# Check available financial data
print("Movies with Budget > 0 :", (ott_df["budget"] > 0).sum())
print("Movies with Revenue > 0 :", (ott_df["revenue"] > 0).sum())
print("Movies with BOTH Budget & Revenue > 0 :",
      ((ott_df["budget"] > 0) & (ott_df["revenue"] > 0)).sum())

Movies with Budget > 0 : 8880
Movies with Revenue > 0 : 7398
Movies with BOTH Budget & Revenue > 0 : 5375

In [17]:
# Convert release_date to datetime
ott_df["release_date"] = pd.to_datetime(
    ott_df["release_date"],
    errors="coerce"
)

# Check data types
print(ott_df.dtypes)

belongs_to_collection               str
budget                            int64
genres                              str
id                                int64
original_language                   str
overview                            str
production_companies                str
production_countries                str
release_date             datetime64[us]
revenue                         float64
runtime                         float64
spoken_languages                    str
cast                                str
crew                                str
keywords                            str
dtype: object

In [18]:
# Create Profit
ott_df["profit"] = ott_df["revenue"] - ott_df["budget"]

# Create ROI
ott_df["roi"] = (ott_df["revenue"] - ott_df["budget"]) / ott_df["budget"]

# Display first few rows
ott_df[["budget", "revenue", "profit", "roi"]].head()

     budget      revenue       profit        roi
0  30000000  373554033.0  343554033.0  11.451801
1  65000000  262797249.0  197797249.0   3.043035
2         0          0.0          0.0        NaN
3  16000000   81452156.0   65452156.0   4.090760
4         0   76578911.0   76578911.0        inf

In [19]:
ott_df["roi"].describe()

C:\Users\vedul\AppData\Roaming\Python\Python312\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    1.090300e+04
mean              inf
std               NaN
min     -1.000000e+00
25%     -1.000000e+00
50%      2.735115e-01
75%      6.262519e+00
max               inf
Name: roi, dtype: float64

In [20]:
ott_df["roi"].isnull().sum()

np.int64(34530)

In [21]:
# Keep only movies with valid budget and revenue
model_df = ott_df[
    (ott_df["budget"] > 0) &
    (ott_df["revenue"] > 0)
].copy()

# Recalculate Profit
model_df["profit"] = model_df["revenue"] - model_df["budget"]

# Recalculate ROI
model_df["roi"] = model_df["profit"] / model_df["budget"]

print(model_df.shape)

print(model_df["roi"].describe())

(5375, 17)
count    5.375000e+03
mean     5.571109e+03
std      2.169776e+05
min     -9.999995e-01
25%     -2.128177e-01
50%      1.057193e+00
75%      3.242222e+00
max      1.239638e+07
Name: roi, dtype: float64

In [22]:
print(model_df.shape)

print(model_df["roi"].describe())

(5375, 17)
count    5.375000e+03
mean     5.571109e+03
std      2.169776e+05
min     -9.999995e-01
25%     -2.128177e-01
50%      1.057193e+00
75%      3.242222e+00
max      1.239638e+07
Name: roi, dtype: float64

In [23]:
model_df.nlargest(10, "roi")[
    ["id",
     "budget",
     "revenue",
     "profit",
     "roi"]
]

           id  budget      revenue       profit           roi
3999    13703       1   12396383.0   12396382.0  1.239638e+07
3341     3082       1    8500000.0    8499999.0  8.499999e+06
14367   14968       8   33579813.0   33579805.0  4.197476e+06
22263  114903       1    2755584.0    2755583.0  2.755583e+06
2307     8856     113  115103979.0  115103866.0  1.018618e+06
25971   78383      10   10000000.0    9999990.0  9.999990e+05
16657   50217      93    2500000.0    2499907.0  2.688072e+04
14187   23827   15000  193355800.0  193340800.0  1.288939e+04
8210     1435     218    1162014.0    1161796.0  5.329339e+03
2594     2667   60000  248000000.0  247940000.0  4.132333e+03

In [24]:
model_df.nsmallest(10, "roi")[
    ["id",
     "budget",
     "revenue",
     "profit",
     "roi"]
]

           id    budget  revenue      profit       roi
7015    14844  23000000     12.0 -22999988.0 -0.999999
8106    18475  16000000     12.0 -15999988.0 -0.999999
2662    48781   6400000      6.0  -6399994.0 -0.999999
12942   38140   4002313      6.0  -4002307.0 -0.999999
17519   33927  10000000     18.0  -9999982.0 -0.999998
6735    10944  12000000     23.0 -11999977.0 -0.999998
2881   108346   2000000      7.0  -1999993.0 -0.999996
45366  280422    750000      3.0   -749997.0 -0.999996
11915    2196   9000000     46.0  -8999954.0 -0.999995
34250  237214    390000      3.0   -389997.0 -0.999992

In [25]:
model_df.nlargest(10, "roi")[["id","budget","revenue","profit","roi"]]

           id  budget      revenue       profit           roi
3999    13703       1   12396383.0   12396382.0  1.239638e+07
3341     3082       1    8500000.0    8499999.0  8.499999e+06
14367   14968       8   33579813.0   33579805.0  4.197476e+06
22263  114903       1    2755584.0    2755583.0  2.755583e+06
2307     8856     113  115103979.0  115103866.0  1.018618e+06
25971   78383      10   10000000.0    9999990.0  9.999990e+05
16657   50217      93    2500000.0    2499907.0  2.688072e+04
14187   23827   15000  193355800.0  193340800.0  1.288939e+04
8210     1435     218    1162014.0    1161796.0  5.329339e+03
2594     2667   60000  248000000.0  247940000.0  4.132333e+03

In [26]:
model_df.nsmallest(10, "roi")[["id","budget","revenue","profit","roi"]]

           id    budget  revenue      profit       roi
7015    14844  23000000     12.0 -22999988.0 -0.999999
8106    18475  16000000     12.0 -15999988.0 -0.999999
2662    48781   6400000      6.0  -6399994.0 -0.999999
12942   38140   4002313      6.0  -4002307.0 -0.999999
17519   33927  10000000     18.0  -9999982.0 -0.999998
6735    10944  12000000     23.0 -11999977.0 -0.999998
2881   108346   2000000      7.0  -1999993.0 -0.999996
45366  280422    750000      3.0   -749997.0 -0.999996
11915    2196   9000000     46.0  -8999954.0 -0.999995
34250  237214    390000      3.0   -389997.0 -0.999992

In [27]:
model_df["budget"].describe()

count    5.375000e+03
mean     3.110802e+07
std      4.018026e+07
min      1.000000e+00
25%      5.053316e+06
50%      1.700000e+07
75%      4.000000e+07
max      3.800000e+08
Name: budget, dtype: float64

In [28]:
model_df["budget"].quantile([0.01, 0.05, 0.10, 0.25, 0.50])

0.01        5740.0
0.05      500000.0
0.10     1500000.0
0.25     5053316.0
0.50    17000000.0
Name: budget, dtype: float64

In [29]:
model_df["roi"].quantile([0.95, 0.99, 0.995, 0.999])

0.950        14.727298
0.990        83.160000
0.995       169.080566
0.999    636052.763441
Name: roi, dtype: float64

In [30]:
# Remove extreme ROI outliers (top 1%)
final_df = model_df[model_df["roi"] <= model_df["roi"].quantile(0.99)].copy()

print("Shape:", final_df.shape)

print(final_df["roi"].describe())

Shape: (5321, 17)
count    5321.000000
mean        2.925932
std         7.045987
min        -0.999999
25%        -0.217500
50%         1.025316
75%         3.143675
max        83.000000
Name: roi, dtype: float64

In [31]:
print("Maximum ROI:", final_df["roi"].max())

Maximum ROI: 83.0

In [32]:
model_df = final_df.copy()

In [33]:
# Create Franchise feature
model_df["franchise"] = model_df["belongs_to_collection"].notna().astype(int)

# Check distribution
print(model_df["franchise"].value_counts())

# Remove original JSON column
model_df.drop(columns=["belongs_to_collection"], inplace=True)

franchise
0    4118
1    1203
Name: count, dtype: int64

In [34]:
# Release Year
model_df["release_year"] = model_df["release_date"].dt.year

# Release Month
model_df["release_month"] = model_df["release_date"].dt.month

# Release Quarter
model_df["release_quarter"] = model_df["release_date"].dt.quarter

# Function to determine season
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    elif month in [9, 10, 11]:
        return "Fall"
    else:
        return None

# Release Season
model_df["release_season"] = model_df["release_month"].apply(get_season)

# Remove original release_date column
model_df.drop(columns=["release_date"], inplace=True)

# Check the new columns
model_df[[
    "release_year",
    "release_month",
    "release_quarter",
    "release_season"
]].head()

   release_year  release_month  release_quarter release_season
0          1995             10                4           Fall
1          1995             12                4         Winter
3          1995             12                4         Winter
5          1995             12                4         Winter
8          1995             12                4         Winter

In [35]:
import ast

# Extract genre names
model_df["genre_list"] = model_df["genres"].apply(
    lambda x: [i["name"] for i in ast.literal_eval(x)]
)

# Check first few rows
model_df[["genres", "genre_list"]].head()

,genres,genre_list
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[Animation, Comedy, Family]"
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[Adventure, Fantasy, Family]"
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[Comedy, Drama, Romance]"
5,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","[Action, Crime, Drama, Thriller]"
8,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","[Action, Adventure, Thriller]"

In [36]:
from collections import Counter

# Count all genres
genre_counts = Counter()

for genres in model_df["genre_list"]:
    genre_counts.update(genres)

# Convert to DataFrame
genre_df = (
    pd.DataFrame(
        genre_counts.items(),
        columns=["Genre", "Count"]
    )
    .sort_values(by="Count", ascending=False)
)

genre_df

              Genre  Count
5             Drama   2561
1            Comedy   1836
9          Thriller   1494
7            Action   1406
6           Romance   1002
3         Adventure    953
8             Crime    855
11  Science Fiction    631
13           Horror    568
2            Family    525
4           Fantasy    505
12          Mystery    439
0         Animation    288
10          History    232
14              War    199
18            Music    190
17          Western     89
16      Documentary     56
15          Foreign     33
19         TV Movie      1

In [37]:
genre_df.head(20)

              Genre  Count
5             Drama   2561
1            Comedy   1836
9          Thriller   1494
7            Action   1406
6           Romance   1002
3         Adventure    953
8             Crime    855
11  Science Fiction    631
13           Horror    568
2            Family    525
4           Fantasy    505
12          Mystery    439
0         Animation    288
10          History    232
14              War    199
18            Music    190
17          Western     89
16      Documentary     56
15          Foreign     33
19         TV Movie      1

In [38]:
#Avg ROI by genre

# Explode the genre list so each genre gets its own row
genre_roi = model_df.explode("genre_list")

# Calculate statistics
genre_roi_summary = (
    genre_roi.groupby("genre_list")["roi"]
    .agg(
        Movie_Count="count",
        Average_ROI="mean",
        Median_ROI="median",
        ROI_STD="std"
    )
    .sort_values("Average_ROI", ascending=False)
)

genre_roi_summary

                 Movie_Count  Average_ROI  Median_ROI    ROI_STD
genre_list
TV Movie                   1     7.400000    7.400000        NaN
Documentary               56     5.827627    1.136847  12.037575
Horror                   568     4.535570    1.392884   9.967621
Music                    190     3.857069    1.440477   8.619260
Animation                288     3.368440    1.708322   6.884087
Western                   89     3.206550    0.804007   9.542560
Romance                 1002     3.195291    1.057972   7.504161
Family                   525     3.076766    1.471329   6.594896
Adventure                953     3.023054    1.289673   7.101849
Comedy                  1836     2.841039    1.089431   6.447783
Thriller                1494     2.677194    0.955023   6.836031
Drama                   2561     2.667993    0.727359   6.796838
Science Fiction          631     2.651932    1.000000   7.031109
Fantasy                  505     2.519157    1.119890   5.596651
History                  232     2.447191    0.700708   6.212438
War                      199     2.441848    0.887646   4.383041
Mystery                  439     2.288948    0.666667   5.529282
Foreign                   33     2.158545    0.000000   7.003939
Action                  1406     2.149620    1.001942   4.791792
Crime                    855     2.071826    0.864866   4.263909

In [39]:
#director extraction

import ast

def extract_director(crew):
    try:
        crew = ast.literal_eval(crew)
        for person in crew:
            if person["job"] == "Director":
                return person["name"]
    except:
        return None

model_df["director"] = model_df["crew"].apply(extract_director)

model_df[["director"]].head()

          director
0    John Lasseter
1     Joe Johnston
3  Forest Whitaker
5     Michael Mann
8      Peter Hyams

In [40]:
#keywords

def extract_keywords(keywords):
    try:
        keywords = ast.literal_eval(keywords)
        return [k["name"] for k in keywords]
    except:
        return []

model_df["keyword_list"] = model_df["keywords"].apply(extract_keywords)

model_df[["keyword_list"]].head()

                                        keyword_list
0  [jealousy, toy, boy, friendship, friends, riva...
1  [board game, disappearance, based on children'...
3  [based on novel, interracial relationship, sin...
5  [robbery, detective, bank, obsession, chase, s...
8    [terrorist, hostage, explosive, vice president]

In [41]:
#production companies

def extract_companies(companies):
    try:
        companies = ast.literal_eval(companies)
        return [c["name"] for c in companies]
    except:
        return []

model_df["company_list"] = model_df["production_companies"].apply(extract_companies)

model_df[["company_list"]].head()

                                        company_list
0                          [Pixar Animation Studios]
1  [TriStar Pictures, Teitler Film, Interscope Co...
3           [Twentieth Century Fox Film Corporation]
5  [Regency Enterprises, Forward Pass, Warner Bros.]
8  [Universal Pictures, Imperial Entertainment, S...

In [42]:
#spoken languages

def extract_languages(languages):
    try:
        languages = ast.literal_eval(languages)
        return [l["name"] for l in languages]
    except:
        return []

model_df["language_list"] = model_df["spoken_languages"].apply(extract_languages)

model_df[["language_list"]].head()

         language_list
0            [English]
1  [English, Français]
3            [English]
5   [English, Español]
8            [English]

In [43]:
#Production Countries
def extract_countries(countries):
    try:
        countries = ast.literal_eval(countries)
        return [c["name"] for c in countries]
    except:
        return []

model_df["country_list"] = model_df["production_countries"].apply(extract_countries)

model_df[["country_list"]].head()

                 country_list
0  [United States of America]
1  [United States of America]
3  [United States of America]
5  [United States of America]
8  [United States of America]

In [44]:
model_df.drop(columns=[
    "genres",
    "cast",
    "crew",
    "keywords",
    "production_companies",
    "production_countries",
    "spoken_languages"
], inplace=True)

In [45]:
model_df.info()

<class 'pandas.DataFrame'>
Index: 5321 entries, 0 to 45389
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             5321 non-null   int64
 1   id                 5321 non-null   int64
 2   original_language  5321 non-null   str
 3   overview           5310 non-null   str
 4   revenue            5321 non-null   float64
 5   runtime            5320 non-null   float64
 6   profit             5321 non-null   float64
 7   roi                5321 non-null   float64
 8   franchise          5321 non-null   int64
 9   release_year       5321 non-null   int32
 10  release_month      5321 non-null   int32
 11  release_quarter    5321 non-null   int32
 12  release_season     5321 non-null   str
 13  genre_list         5321 non-null   object
 14  director           5316 non-null   str
 15  keyword_list       5321 non-null   object
 16  company_list       5321 non-null   object
 17  language_list      5321 non-null   object
 18  country_list       5321 non-null   object
dtypes: float64(4), int32(3), int64(3), object(5), str(4)
memory usage: 2.4+ MB

In [46]:
model_df.head()

,budget,id,original_language,overview,revenue,runtime,profit,roi,franchise,release_year,release_month,release_quarter,release_season,genre_list,director,keyword_list,company_list,language_list,country_list
0,30000000,862,en,"Led by Woody, Andy's toys live happily in his ...",373554033.0,81.0,343554033.0,11.451801,1,1995,10,4,Fall,"[Animation, Comedy, Family]",John Lasseter,"[jealousy, toy, boy, friendship, friends, riva...",[Pixar Animation Studios],[English],[United States of America]
1,65000000,8844,en,When siblings Judy and Peter discover an encha...,262797249.0,104.0,197797249.0,3.043035,0,1995,12,4,Winter,"[Adventure, Fantasy, Family]",Joe Johnston,"[board game, disappearance, based on children'...","[TriStar Pictures, Teitler Film, Interscope Co...","[English, Français]",[United States of America]
3,16000000,31357,en,"Cheated on, mistreated and stepped on, the wom...",81452156.0,127.0,65452156.0,4.090760,0,1995,12,4,Winter,"[Comedy, Drama, Romance]",Forest Whitaker,"[based on novel, interracial relationship, sin...",[Twentieth Century Fox Film Corporation],[English],[United States of America]
5,60000000,949,en,"Obsessive master thief, Neil McCauley leads a ...",187436818.0,170.0,127436818.0,2.123947,0,1995,12,4,Winter,"[Action, Crime, Drama, Thriller]",Michael Mann,"[robbery, detective, bank, obsession, chase, s...","[Regency Enterprises, Forward Pass, Warner Bros.]","[English, Español]",[United States of America]
8,35000000,9091,en,International action superstar Jean Claude Van...,64350171.0,106.0,29350171.0,0.838576,0,1995,12,4,Winter,"[Action, Adventure, Thriller]",Peter Hyams,"[terrorist, hostage, explosive, vice president]","[Universal Pictures, Imperial Entertainment, S...",[English],[United States of America]

In [48]:
# ==========================================
# Save Final Processed Dataset
# ==========================================

import os

# Create folder if it doesn't exist
os.makedirs("../dataset/processed", exist_ok=True)

# Save processed dataset
model_df.to_csv("../dataset/processed/model_dataset.csv", index=False)

print("✅ model_dataset.csv saved successfully!")

✅ model_dataset.csv saved successfully!